// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/messaging.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "messaging";

export interface ChatStreamResponse {
  roomId: string;
  message: Message | undefined;
}

export interface ChatStreamRequest {
  roomId: string;
}

export interface SendMessageRequest {
  roomId: string;
  message: Message | undefined;
}

export interface Empty {
}

export interface Message {
  messageId: string;
  senderId: string;
  receiverId: string;
  content: string;
  timestamp: number;
}

export const MESSAGING_PACKAGE_NAME = "messaging";

export interface MessagingServiceClient {
  sendMessage(request: SendMessageRequest): Observable<Empty>;

  chatStream(request: Observable<ChatStreamRequest>): Observable<ChatStreamResponse>;
}

export interface MessagingServiceController {
  sendMessage(request: SendMessageRequest): Promise<Empty> | Observable<Empty> | Empty;

  chatStream(request: Observable<ChatStreamRequest>): Observable<ChatStreamResponse>;
}

export function MessagingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendMessage"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MessagingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["chatStream"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MessagingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MESSAGING_SERVICE_NAME = "MessagingService";
